CREATE TABLE PERSONAL_USER_INFOMATION
(
    MOBILE         VARCHAR2(11 CHAR)   NOT NULL,
    TRUENAME       VARCHAR2(10 CHAR)       NULL,
    QUESTION       VARCHAR2(50 CHAR)       NULL,
    ANSWER         VARCHAR2(50 CHAR)       NULL,
    GRADE          NUMBER(2,0)             NULL,
    GENDER         NUMBER(1,0)             NULL,
    BIRTHDAY       DATE                    NULL,
    CONSTELLATION  NUMBER(2,0)             NULL,
    ADDRESS        VARCHAR2(500 CHAR)      NULL,
    SIGNS          VARCHAR2(1000 CHAR)     NULL,
    EMAIL          VARCHAR2(100 CHAR)      NULL,
    QQ             VARCHAR2(12 CHAR)       NULL,
    MSN            VARCHAR2(100 CHAR)      NULL,
    HEAD_PIC       VARCHAR2(100 CHAR)      NULL,
    HOME           VARCHAR2(100 CHAR)      NULL,
    HEIGHT         NUMBER(3,0)             NULL,
    WEIGHT         NUMBER(4,0)             NULL,
    BODYTYPE       NUMBER(1,0)             NULL,
    BLOODTYPE      NUMBER(1,0)             NULL,
    ENJOY_BOOKTYPE NUMBER(3,0)             NULL,
    PERSONALITY    VARCHAR2(50 CHAR)       NULL,
    NATIVE_PLACE   VARCHAR2(100 CHAR)      NULL,
    EDUCATION      VARCHAR2(100 CHAR)      NULL,
    INTEREST       VARCHAR2(500 CHAR)      NULL,
    INCOME         NUMBER(1,0)             NULL,
    JOBS           VARCHAR2(100 CHAR)      NULL,
    FEELING        NUMBER(2,0)             NULL,
    MARITAL_STATUS NUMBER(1,0)             NULL,
    IS_SMOKING     NUMBER(1,0)             NULL,
    IS_DRINK       NUMBER(1,0)             NULL,
    INTRODUCTION   VARCHAR2(500 CHAR)      NULL,
    ENJOY_BODY     NUMBER(1,0)             NULL,
    ENJOY_BOOK     VARCHAR2(500 CHAR)      NULL,
    NICKNAME       VARCHAR2(100 CHAR)      NULL
)
/
ALTER TABLE PERSONAL_USER_INFOMATION ADD CONSTRAINT
    PK_PERSONAL_USER_INFORMATION PRIMARY KEY (MOBILE)
/


CREATE TABLE PERSONAL_USER_LOGIN
(
    MOBILE       VARCHAR2(11 CHAR)  NOT NULL,
    LOGINNAME    VARCHAR2(100 CHAR)     NULL,
    PASSWD       VARCHAR2(50 CHAR)      NULL,
    LOGIN_STATUS NUMBER(1,0)            NULL,
    USER_TYPE    NUMBER(1,0)            NULL,
    USER_STATUS  NUMBER(1,0)            NULL
)
/
ALTER TABLE PERSONAL_USER_LOGIN
    ADD CONSTRAINT PK_PERSONAL_USER_LOGIN
    PRIMARY KEY (MOBILE)
 
/



CREATE TABLE READER_BUSSINESS_PACKGROUP
(
    PACK_GROUP_ID         NUMBER(10,0)  NOT NULL,
    PK_NAME               VARCHAR2(64)  NOT NULL,
    PK_COMMENT            VARCHAR2(255)     NULL,
    PK_USER_STATUS        NUMBER(1,0)   NOT NULL,
    PK_SHOW_TYPE          NUMBER(1,0)   NOT NULL,
    PK_FIRST_TEM_ID       NUMBER(10,0)  NOT NULL,
    PK_DELETE_STATUS      NUMBER(1,0)   NOT NULL,
    PK_RES_TEM_ID         NUMBER(10,0)      NULL,
    IN_DATE               DATE          NOT NULL,
    CREATOR_ID            NUMBER(10,0)  NOT NULL,
    PK_SECOND_TEM_ID      NUMBER(10,0)      NULL,
    PK_G_TEM_ID           NUMBER(10,0)      NULL,
    PK_RES_SENCOND_TEM_ID NUMBER(10,0)      NULL,
    PK_RES_G_TEM_ID       NUMBER(10,0)      NULL,
    P_USERS               VARCHAR2(255)      NULL,
	MODIFY_ID	  NUMBER(10,0)      NULL,
	MODIFY_TIME	  DATE              NULL,	
     constraint PK_READER_BUSSINESS_PACKGROUP primary key (PACK_GROUP_ID)
)
/
CREATE TABLE READER_BUSSINESS_PG_AREA
(
    PRODUCTID     VARCHAR2(9 CHAR) NOT NULL,
    AREA_ID       VARCHAR2(3 CHAR) NOT NULL,
    PACK_GROUP_ID NUMBER(10,0)     NOT NULL,
  constraint PK_BUSSINESS_PG_AREA primary key (PRODUCTID,AREA_ID)
)
/
CREATE TABLE READER_BUSSINESS_PRODUCT
(
    PRODUCTID     VARCHAR2(9)   NOT NULL,
    S_NAME        VARCHAR2(64)  NOT NULL,
    CHANNEL_ID    CHAR(4 CHAR)  NOT NULL,
    STATUS        NUMBER(1,0)   NOT NULL,
    S_TYPE        NUMBER(1,0)   NOT NULL,
    IS_ADAPTER    NUMBER(1,0)   NOT NULL,
    IS_NARROW     NUMBER(1,0)   NOT NULL,
    IN_DATE       DATE          NOT NULL,
    CREATOR_ID    NUMBER(10,0)  NOT NULL,
    P_USERS       VARCHAR2(255)     NULL,
	MODIFY_ID	  NUMBER(10,0)      NULL,
	MODIFY_TIME	  DATE              NULL,	
 constraint PK_BUSSINESS_PRODUCT primary key (PRODUCTID)
)
/
CREATE SEQUENCE READER_BUSSINESS_COLUMN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    NOCACHE
    NOORDER
/


CREATE TABLE READER_BUSSINESS_TEMPLATE
(
    TEMPLATE_ID        NUMBER(10,0)       NOT NULL,
    T_CONTENT          CLOB                   NULL,
    T_CREATETIME       TIMESTAMP(6)           NULL,
    CHANNEL_CREATOR    NUMBER(10,0)           NULL,
    CHANNEL_MODIFYTIME TIMESTAMP(6)           NULL,
    T_MODIFIER         NUMBER(10,0)           NULL,
    T_SHOW_TYPE        NUMBER(2,0)       NOT NULL,
    T_SIGN_TYPE        NUMBER(2,0)       NOT NULL,
    IS_USE             NUMBER(1,0)       NOT NULL,
    T_NAME             VARCHAR2(50 CHAR)  NOT NULL,
    T_USERS            VARCHAR2(255 CHAR)     NULL,
    T_ATTACH_ID        NUMBER(2,0)       NOT NULL,
    T_CATALOG_ID	 NUMBER(4,0)       NOT NULL,
    DOWN_PAGE_ID       NUMBER(10,0)           NULL,
	PRE_CONTENT			 CLOB                   NULL,
	PRE_STATUS		 NUMBER(1,0)       NOT NULL,
    constraint PK_BUSSINESS_TEMPLATE primary key (TEMPLATE_ID)
)
/
CREATE TABLE READER_BUSSINESS_TEM_CATALOG
(
    T_ATTACH_ID NUMBER(4,0)       NOT NULL,
    IN_DATE     TIMESTAMP(6)       NOT NULL,
    CREATOR_ID  NUMBER(10,0)       NOT NULL,
    TYPE_NAME   VARCHAR(50) NOT NULL,
    constraint PK_BUSSINESS_TEM_CATALOG primary key (T_ATTACH_ID)
)
/
CREATE TABLE READER_BUSSINESS_TEM_DEFAULT
(
    PAGE_TYPE  NUMBER(2,0)       NOT NULL,
    WAP_TYPE     NUMBER(2,0)       NOT NULL,
    TEMPLATE_ID  NUMBER(10,0)       NOT NULL,
    constraint PK_BUSSINESS_TEM_DEFAULT primary key (PAGE_TYPE,WAP_TYPE)
)
/
CREATE TABLE READER_BUSSINESS_TEM_TYPE
(
    T_ATTACH_ID NUMBER(2,0)       NOT NULL,
    IN_DATE     TIMESTAMP(6)       NOT NULL,
    CREATOR_ID  NUMBER(10,0)       NOT NULL,
    TYPE_NAME   VARCHAR(50) NOT NULL,
    constraint PK_BUSSINESS_TEM_TYPE primary key (T_ATTACH_ID)
)
/
INSERT INTO READER_BUSSINESS_TEM_TYPE T ( T_ATTACH_ID, IN_DATE, CREATOR_ID, TYPE_NAME ) 
        VALUES ( 1, TO_DATE( '07-11-2009 15:36:16', 'MM-DD-YYYY HH24:MI:SS' ), 1, '首页模板' )
/
INSERT INTO READER_BUSSINESS_TEM_TYPE T ( T_ATTACH_ID, IN_DATE, CREATOR_ID, TYPE_NAME ) 
        VALUES ( 2, TO_DATE( '07-14-2009 02:55:34', 'MM-DD-YYYY HH24:MI:SS' ), 1, '栏目模板' )
/
INSERT INTO READER_BUSSINESS_TEM_TYPE T ( T_ATTACH_ID, IN_DATE, CREATOR_ID, TYPE_NAME ) 
        VALUES ( 3, TO_DATE( '07-14-2009 02:55:42', 'MM-DD-YYYY HH24:MI:SS' ), 1, '资源模板' )
/
INSERT INTO READER_BUSSINESS_TEM_TYPE T ( T_ATTACH_ID, IN_DATE, CREATOR_ID, TYPE_NAME ) 
        VALUES ( 4, TO_DATE( '07-14-2009 02:55:53', 'MM-DD-YYYY HH24:MI:SS' ), 1, '详情模板' )
/

INSERT INTO READER_BUSSINESS_TEM_TYPE T ( T_ATTACH_ID, IN_DATE, CREATOR_ID, TYPE_NAME ) 
        VALUES ( 5, TO_DATE( '07-14-2009 02:55:42', 'MM-DD-YYYY HH24:MI:SS' ), 1, '资费模板' )
/
INSERT INTO READER_BUSSINESS_TEM_TYPE T ( T_ATTACH_ID, IN_DATE, CREATOR_ID, TYPE_NAME ) 
        VALUES ( 6, TO_DATE( '07-14-2009 02:55:53', 'MM-DD-YYYY HH24:MI:SS' ), 1, '通用模板' )
/